create table if not exists public.question_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  question_id integer not null,
  question_text text not null,
  category text not null,
  category_label text not null,
  reason text not null check (
    reason in (
      'confusing',
      'wrong_answer',
      'outdated',
      'image_issue',
      'other'
    )
  ),
  comment text,
  source text not null,
  image_url text,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (
    status in ('pending', 'reviewing', 'resolved', 'rejected')
  ),
  admin_notes text,
  app_version text,
  platform text
);

alter table public.question_reports enable row level security;

create policy "Users can create question reports"
  on public.question_reports
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can read their own question reports"
  on public.question_reports
  for select
  to authenticated
  using (auth.uid() = user_id);

create index if not exists question_reports_status_created_at_idx
  on public.question_reports (status, created_at desc);

create index if not exists question_reports_question_id_idx
  on public.question_reports (question_id);
